### ISSUE TITLE
Demo mode

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#454] opened 2019-10-02 04:05 UTC
## User story
As a potential instructor or admin user,
I want to be able to view a demo of the application without needing to install it on my computer
So that I can make an educated decision on whether I want to use this for my class.

**Comment by bryan-gilbert** [comment] 2019-12-23 00:49
duplicate of #482 
(yes this issue was registered first, just that 482 has more information)

**Closed by bryan-gilbert** 2019-12-23 00:49 UTC
Labels: Investigation, POST-MVP, f-demo, help, ~Feature
